### PR TITLE
PetAnimation Sprite -> Gif Update/general refactoring

### PR DESCRIPTION
**Pull request by andrewcalimlim**
Mainly update PetAnimation to reflect gif usage instead of sprite storage, basically the last needed to do before integration can begin.

- removed run method since we're using gifs and no longer need to loop through sprites
-updated arrays with gif file types instead of sprites
-updated setting current animation method to update current gif as well 
-updated gif file name storage array to be more intuitive

We should be able to change animations of the pet simply by setting the animation ("bathing" for example) and then call the current gif to get the appropriate gif file name ("bathing-default.gif") which can be then displayed.

### CODE REVIEW

**Review by Tomi-Tanaka — CHANGES_REQUESTED** [review]
I think it looks good, though the saving and loading methods can probably be removed now that we have a class for handling that

**Comment by andrewcalimlim** [comment]
> I think it looks good, though the saving and loading methods can probably be removed now that we have a class for handling that

good point, i just removed them now

**Review by Tomi-Tanaka — APPROVED** [review]

**Review by hingler — APPROVED** [review]
Looks good -- make sure to remove the main methods at some point as well

**Comment by andrewcalimlim** [comment]
> Looks good -- make sure to remove the main methods at some point as well

took care of that as well just now

**Pull request merged**
